spring:
  application:
    name: INFOSALUD
  # Configuracion basica de H2
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
    DB_CLOSE_ON_EXIT: FALSE
    platform: h2
  # Habilitar consola H2
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  # Configuracion de JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  output:
    ansi:
      enabled: ALWAYS
# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
  api-docs:
    path: /api-docs
logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.hibernate: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR